/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	// tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

	// But you can create a sidebar manually
	/*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */

	// 不同页面使用不同目录
	frontEndSidebar: [{ type: 'autogenerated', dirName: 'frontend' }],
	healthSidebar: [{ type: 'autogenerated', dirName: 'health' }],
	financialSidebar: [{ type: 'autogenerated', dirName: 'finance' }],
	colorModulationSidebar: [{ type: 'autogenerated', dirName: 'color-modulation' }],
	photoGraphSidebar: [{ type: 'autogenerated', dirName: 'photograph' }],
	backEndSidebar: [{ type: 'autogenerated', dirName: 'backend' }],
	travelSidebar: [{ type: 'autogenerated', dirName: 'travel' }],
	toolsSidebar: [{ type: 'autogenerated', dirName: 'tools' }],
	anyThing: [{ type: 'autogenerated', dirName: 'others' }],
	mind: [{ type: 'autogenerated', dirName: 'psychology' }],
	ai: [{ type: 'autogenerated', dirName: 'artificial-intelligence' }],
};

module.exports = sidebars;
