# This is a basic workflow to help you get started with Actions

name: deploy_website

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '22.x'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install npm dependencies
        run: pnpm install
      
      - name: Show folder files
        run: ls -all $GITHUB_WORKSPACE/

      - name: Run build task
        run: pnpm build

      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build

